version: '3.8'
services:
  db:
    image: mysql:8
    container_name: bank-db
    restart: always
    environment:
      MYSQL_DATABASE: bankdb
      MYSQL_USER: bankuser
      MYSQL_PASSWORD: bankpass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3308:3306"
    volumes:
      - ./src/main/resources:/docker-entrypoint-initdb.d