spring:
  datasource:
    url: jdbc:mysql://localhost:3308/bankdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: bankuser
    password: bankpass
    driver-class-name: com.mysql.cj.jdbc.Driver

  liquibase:
    enabled: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8095

jwt:
  secret: "l6Ps2QirSWRG542fltpHJwp3vWQ5gIyOlyf8Ft6McZY="
  expiration: 3600000
